config/routes.rb
Rails.application.routes.draw do

  root to: 'sites#index'

  ## main routing
  resources :users do 
    resources :courses do 
      resources :polls do 
        resources :replies do
        end
      end
    end
  end

  ## for showing courses to the public
  ## to see courses the user isn't necessarily in
  resources :courses do 
    resources :polls do
    end
  end

  ## for creating new polls, only links user and polls they created
  resources :users do 
    resources :polls do 
    end
  end

  ## for showing all replies by a specific user
  # resources :users do 
  #   resources :replies do 
  #   end 
  # end

  post '/join_course' => 'courses#join_course'
  post '/leave_course' => 'courses#leave_course'

  post 'send_sms' => 'sendtexts#send_text_message'
  # get 'send_sms' => 'sendtexts#send_text_message'
  post 'sms' => 'receive_messages#index'
  # ## testing
  get 'sms' => 'receive_messages#index'

  # post '/search', to: 'replies#search'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  # for development only
  get '/logout' => 'sessions#destroy'
  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :polls, dependent: :destroy
	has_many :replies
	has_many :affiliations, dependent: :destroy
	has_many :courses, :through => :affiliations 

	## validations go here
	# name validations still need to be handled in users_controller to avoid app_killing errors
	#validates :first_name, presence: true
	#validates :last_name, presence: true
	## regex on email, sms_phone_number format
	validates :email, presence: true, uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}, on: :create
	validates :sms_phone_number, presence: true, length: {minimum: 6}, on: :create

	## need to learn about Rails single table inheritance
	## uses type, but then need to create child classes
	## for student, teacher, admin etc

	def self.authenticate email, password 
		User.find_by_email(email).try(:authenticate, password)
	end

	## set password reset goes here
	# def set_password_reset
	# 	self.code = SecureRandom.urlsafe_base64
	# 	self.expires_at = 4.hours.from_now
	# 	self.save!
	# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, :except => [:index, :new, :create, :join_course, :leave_course]
	before_action :is_authenticated?, :except => [:new, :create]
	before_action :correct_user?, :except =>[:index, :new, :create,  :join_course, :leave_course]


	def index
		## ok if not current user
		@users = User.all
	end

	def show
		## validate that this is the correct user to see this User Home page
		if correct_user?
			@polls = @user.polls
			@courses = @user.courses
			## access via @poll.replies
		else
			redirect_to user_path(@current_user.id), :notice => "You are not authorized to view this user's page"
		end
	end

	def new
		## this is the signup route, don't need current user check
		## if user is logged in, don't want them to sign up
		if session[:user_id] != nil
			redirect_to user_path(session[:user_id] )
		else
			@user = User.new
		end
	end

	def create
		if session[:user_id] == nil
			@user = User.new(user_params)
			if @user.save # user saved successfully
				auth_user = User.authenticate(@user.email, @user.password)
				# reformat sms number to be seven-digit string, further validation?
				@user.sms_phone_number = @user.sms_phone_number.gsub(/\D/, '')
				@user.save
				if auth_user
					session[:user_id] = @user.id
					# alert admin about new signup
					sms_user_alert("New user created on Fist of Five website: ")
					redirect_to user_path(@user.id), :notice => "Signed up!"
				end
			else # user not saved successfully?
				if User.find_by_email(@user.email)
					redirect_to signup_path, :notice => 'An account with that email already exists'
				elsif @user.password && @user.password.length < 6
					redirect_to signup_path, :notice => "Password must be at least six characters"
				elsif @user.password != @user.password_confirmation
					redirect_to signup_path, :notice => "Password must match password confirmation"
				# add validation for email format
				elsif @user.sms_phone_number == ""
					redirect_to signup_path, :notice => "Please enter a phone number to receive SMS text messages"
				# add validation for seven-digit number
				else
					flash[:error] = @user.errors.full_messages.to_sentence
						
				end
			end	
		else
			#someone is already logged in and trying to signup, not allowed
			session[:user_id] = nil
			redirect_to login_path, :notice => "Please log in again"
		end
	end

	# only the user should be able to edit their own account
	def edit
	end

	def update
		@user.update_attributes(user_params)
		redirect_to user_path, :notice => "Profile updated"
	end

	# only the user should be able to destroy their own account
	def destroy
		sms_user_alert("User deleted: ")
		@user.destroy
		session[:user_id] = nil
		redirect_to root_path, :notice => "Profile deleted"
	end


	private

		def find_user
			@user = User.find(params[:id])
			## allows only the user to see this??
			redirect_to root_path unless @user
		end

		def user_params
			params.require(:user).permit(:first_name, :last_name, :sms_phone_number, :email, :password, :password_confirmation, :opt_out)
		end

		def correct_user?
			@user = User.find(params[:id])
			@current_user ||= User.find_by(id: session[:user_id])
			## returns result of this comparison
			@user == @current_user
		end

		def current_user_affiliated?
			@course = find_course
			if (@course.users.find_by_id(@current_user.id))
				@user_affiliated = true
			else
				@user_affiliated = false
			end
		end

		def sms_user_alert (message_content)
			formatted_num = [ENV['ADMIN_NUMBER']]
			user_email = @user.email
			# message_content = "New user created or deleted"
			message_site = " http://fistof5.herokuapp.com"

			twilio_sid = ENV['TWILIO_ACCOUNT_SID']
			twilio_token = ENV['TWILIO_AUTH_TOKEN']
			twilio_phone_number = ENV['TWILIO_NUMBER']

			@twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

			@twilio_client.account.sms.messages.create(
			:from => "+1#{twilio_phone_number}",
			:to => "+1#{formatted_num}",
			:body => message_content + user_email + message_site
			)
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<!-- _user_form.html.erb -->
<!-- signup partial -->
<div class="row">
	<%= form_for @user, html: {class: "form-horizontal"} do |f|  %>
	<fieldset class="col-md-offset-3 col-md-6">
		<legend><%= form_title  %></legend>
		<div class="form-group">
			<%= f.text_field :first_name, class: "form-control", placeholder: "First name", autofocus: true  %>	
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.text_field :last_name, class: "form-control", placeholder: "Last name"  %>				
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.text_field :sms_phone_number, class: "form-control", placeholder: "Phone number (for SMS text messages)"  %>				
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.text_field :email, class: "form-control", placeholder: "Email"  %>				
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.password_field :password, class: "form-control", placeholder: "Password"  %>
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password"  %>
		</div>	<!-- closes form-group -->
		<div class="form-group ">
			<%= f.radio_button :opt_out, 'false', :checked => true %> 
 			<%= label :opt_out_false, 'Stay connected via SMS' %><br>
			<%= f.radio_button :opt_out, 'true' %>
  			<%= label :opt_out_true, 'Opt-out of receiving polls' %>
		</div>
		<div class="form-group">
			<%= f.submit button_label, class: "btn btn-form btn-warning" %>
		</div>	<!-- closes form-group -->
	
	</fieldset>
	<% end %><!--  ends form for -->
</div>

app/views/users/_user_navbar.html.erb
<!-- _user_navbar.html.erb -->
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-header">
		<!-- collapse has to do with working with mobile -->
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<%= link_to "Fo5", root_path, class: "navbar-brand" %>
               <% if page_title %>
                  <a class="navbar-brand"><%= page_title %></a>
                <% end %>
            
              <% flash.each do |k,v| %>
                <a class="navbar-brand flash" id="<%= k %>"><em><%= v %></em></a>
              <% end %>
          
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">

      <ul class="nav navbar-nav navbar-right">
      <!-- control what navigation is seen, View courses etc, start without needing user-->
      <!-- Leaving out replies -->
        <!-- <#% if @reply && @reply.id %> -->
          <!-- <li>REPLY NAVBAR</li> -->
<!--           <li><%#= link_to "View All Results", user_poll_replies_path(@user.id, @poll.id)  %></li> -->

        <% if @poll && @poll.course_id %>
          <!-- <li>POLL NAVBAR</li> -->
          <li><%= link_to "View All Polls", course_polls_path(@poll.course_id)  %></li>

        <% elsif @course && @course.id %>
          <li><%= link_to "View All Courses", courses_path %></li>

        <% elsif @user && @user.id %>
         <!--  <li>USER NAVBAR</li> -->
            <li><%= link_to "View All Users", users_path %></li>
        <% end %>
          
        <!-- Behavoir of user shortcut, login, logout, signup -->
        <% if @current_user %>
         <!--  <#% @user = @current_user %> -->
          <li class="active"><%= link_to @current_user.first_name ||  @current_user.email , user_path(@current_user.id)  %></li>
          <li><%= link_to "Logout", logout_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "Log in", login_path  %></li>
          <li><%= link_to "Sign up", signup_path  %></li>
        <% end %>
        <li><a href="#"></a></li>
      </ul>
  </div>
</div>

app/views/users/_user_preview.html.erb
<!-- _user_preview.html.erb -->

<%= user.first_name  %> <%= user.last_name  %> <br>

<ul>
	<li><i><%= user.email  %></i></li><br>
	<% for course in user.courses.order(:title)  %>
		<li> <%= link_to course.title, course_path(course.id)%></li><br>
	<% end %>
</ul>

app/views/users/edit.html.erb
<% @page_title = "Edit User" %>
<%= render partial: "user_navbar", locals: {user: @user, page_title: "Edit User"} %>

	<div class="jumbotron">
		<%= render partial: "user_form", locals: {user: @user, form_title: "Edit User Information", button_label: "Save Changes"}   %>
		<%= button_to "Cancel", user_path(@current_user.id), method: :get, class: "btn btn-form btn-danger" %>
	</div>

app/views/users/index.html.erb
<!-- index.html.erb -->
<% @page_title = "Users" %>
<%= render partial: "user_navbar", locals: {user: @user, page_title: "Users"} %>

<%= render partial: "shared/start_main_section"  %>
	<!-- <h3>User name, email course</h3> -->
	<% for user in @users.order(:first_name) do  %>
		<h4><%= render partial: "user_preview", locals: {user: user}  %></h4>
		<!-- <div class="small-spacer"></div> -->
	<% end %>
<%= render partial: "shared/end_main_section"  %>
<%= render partial: "shared/start_sidebar"  %>
	<% if @current_user %>

	<% else %>
		<%= render partial: "shared/participate", locals: {link_class: "btn btn-primary btn-form"} %>
	<% end %>
<%= render partial: "shared/end_sidebar"  %>

app/views/users/new.html.erb
<!-- new.html.erb -->
<!-- signup THIS ONE IS DIFFERENT FROM OTHER USERS VIEWS-->
<% @page_title = "Sign Up" %>

	<div class="jumbotron">
		<h1>Fist of Five</h1>
		<!-- display flash messages -->
		<% flash.each do |k,v| %>
			<h2 id="<%= k %>"><%= v %></h2>
		<% end %>
		<%= render partial: "user_form", locals: {user: @user, form_title: "Sign Up", button_label: "Sign Up"}   %>
		<%= button_to "Return to home page", root_path, method: :get, class: "btn btn-form btn-danger" %>


	</div>

app/views/users/show.html.erb
<!-- home.html.erb -->
<% @page_title = "User Home" %>
<%= render partial: "user_navbar", locals: {user: @user, page_title: "User Home"} %>

<%= render partial: "shared/start_main_section"  %>
	<div class="title-area">
		<h1>Fist of Five</h1>
	</div>
	<div id="current-courses">
		<% if @user.courses.count > 0 %>
		<h3>Your Courses</h3>
			<h4>
			<% for course in @user.courses.order(:id) do  %>
				<%= render partial: "courses/course_preview", locals: {course: course, user: @user }  %>
			<% end %>
			</h4>
		<% else %>
			<h4>
			To participate in Fist of Five polls, first join a course.  <%= link_to "View a list of all courses.", courses_path %>
			<br><br>
			Next you can start a new poll for that course or respond to a poll.
			</h4>
		<% end %>
		
	</div>

<%= render partial: "shared/end_main_section"  %>
<%= render partial: "shared/start_sidebar"  %>
	<div>
		<%= link_to "Account Details", edit_user_path(@user.id), class: "btn btn-sidebar btn-warning"  %><br><br>
		<%= link_to "View All Courses", courses_path, class: "btn btn-sidebar btn-danger" %><br><br>
		<% if @user.courses.count > 0 %>
		<%#= link_to "View All Polls", course_polls_path(@user.courses.first.id), class: "btn btn-sidebar btn-warning" %>
		<% end %>
		<%= render partial: "shared/start_new_poll", locals: {link_class: "btn btn-sidebar btn-primary"}  %><br>
	</div>
	<div class="small-spacer"></div>

<%= render partial: "shared/end_sidebar"  %>