config/routes.rb
Rails.application.routes.draw do

  root to: 'sites#index'

  ## main routing
  resources :users do 
    resources :courses do 
      resources :polls do 
        resources :replies do
        end
      end
    end
  end

  ## for showing courses to the public
  ## to see courses the user isn't necessarily in
  resources :courses do 
    resources :polls do
    end
  end

  ## for creating new polls, only links user and polls they created
  resources :users do 
    resources :polls do 
    end
  end

  ## for showing all replies by a specific user
  # resources :users do 
  #   resources :replies do 
  #   end 
  # end

  post '/join_course' => 'courses#join_course'
  post '/leave_course' => 'courses#leave_course'

  post 'send_sms' => 'sendtexts#send_text_message'
  # get 'send_sms' => 'sendtexts#send_text_message'
  post 'sms' => 'receive_messages#index'
  # ## testing
  get 'sms' => 'receive_messages#index'

  # post '/search', to: 'replies#search'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  # for development only
  get '/logout' => 'sessions#destroy'
  
end

app/views/shared/_create_new_course.html.erb
<!-- _create_new_course.html.erb -->
<%= link_to "Create a new course", new_course_path, class: link_class  %>

app/views/shared/_end_main_section.html.erb
<!-- _end_main_section.html.erb -->
</div>

app/views/shared/_end_sidebar.html.erb
<!-- _end_sidebar.html.erb -->
	</div>
</div> <!-- closes row opened in start_main_section-->

app/views/shared/_participate.html.erb
<!-- _participate.htm.erb -->
<%= link_to "Sign up for Fist of Five", signup_path, class: link_class  %>

app/views/shared/_start_main_section.html.erb
<!-- _start_main_column.html.erb -->
<div class="row <%=@page_title.delete(' ')  %>">
	 <div class="col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-md-6">

app/views/shared/_start_new_poll.html.erb
<!-- _start_new_poll.html.erb -->
<% if @current_user.courses.count > 0 %>
	<%= link_to "Start a new poll", new_user_poll_path(@current_user.id), class: link_class %>
<% end %>

app/views/shared/_start_sidebar.html.erb
<!-- _start_sidebar.html.erb -->
<div class="col-md-offset-1 col-md-4 sidebar">
	<div class="small-spacer"></div>