config/routes.rb
Rails.application.routes.draw do

  root to: 'sites#index'

  ## main routing
  resources :users do 
    resources :courses do 
      resources :polls do 
        resources :replies do
        end
      end
    end
  end

  ## for showing courses to the public
  ## to see courses the user isn't necessarily in
  resources :courses do 
    resources :polls do
    end
  end

  ## for creating new polls, only links user and polls they created
  resources :users do 
    resources :polls do 
    end
  end

  ## for showing all replies by a specific user
  # resources :users do 
  #   resources :replies do 
  #   end 
  # end

  post '/join_course' => 'courses#join_course'
  post '/leave_course' => 'courses#leave_course'

  post 'send_sms' => 'sendtexts#send_text_message'
  # get 'send_sms' => 'sendtexts#send_text_message'
  post 'sms' => 'receive_messages#index'
  # ## testing
  get 'sms' => 'receive_messages#index'

  # post '/search', to: 'replies#search'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  # for development only
  get '/logout' => 'sessions#destroy'
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	# this controller has mostly public views
	before_action :is_authenticated?, except: [:index, :show]
	before_action :is_logged_in? 
	before_action :find_course, except: [:index]	
	# routes have @course, @current_user available

	def index
		# does not require login
		@courses = Course.all
		@current_user
		render "index"
	end

	def show
		# does not require login, @course available
		if @current_user # if logged in
			current_user_affiliated? # is the current user in this course?
			@user_affiliated
		end
		@polls = @course.polls
	end

	def join_course
		# comes from courses/:id page
		@course = Course.find_by_id(params[:format])
		@current_user
		@current_user.courses << @course

		redirect_to user_path(@current_user.id)
	end

	def leave_course
		# comes from courses/:id page
		@course = Course.find_by_id(params[:format])
		@current_user
		# remove course from user courses
		@current_user.courses.delete(@course.id)

		redirect_to user_path(@current_user.id)
	end

	def new
		# if logged in/authenticated
		@course = Course.new
		@current_user
	end

	def edit
		# ok getting to edit page
	end

	def create
		# checked for logged in/is authenticated above
		course = Course.new(course_params)
		if course.save
			redirect_to course_path(course.id), :notice => "Course created"
		else
			flash[:error] = course.errors.full_messages.to_sentence
			redirect_to new_course_path
		end
	end

	def update
		if @course.update_attributes(course_params)
			redirect_to course_path(@course.id), :notice => "Course updated"
		else
			redirect_to course_path(@course.id), :notice => "Error updating"
		end
	end

		# def destroy
		# 	# if this user created it
		# end

private

	def find_course
		id = params[:id]
		@course = Course.find_by_id(id)
	end

	def is_logged_in?
		@current_user ||= User.find_by(id: session[:user_id])
	end

	## as no user is saved on courses, there is no correct user
	# def correct_user?
	# 	@user = find_user
	# 	@current_user ||= User.find_by(id: session[:user_id])
	# 	## returns result of this comparison
	# 	@user == @current_user
	# end

	def current_user_affiliated?
		# is the current user is logged in and affiliated with this course
		@course = find_course
		if (@course.users.count && @course.users.find_by_id(@current_user.id))
			@user_affiliated = true
		else
			@user_affiliated = false
		end
	end

	def course_params
		params.require(:course). permit(:id, :title, :desc, :schedule, :course_time_zone)
	end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_form.html.erb
<!-- course_form -->

<!-- Many fields for entering course information, including opt-out? -->

<div class="row course-form">
	<%= form_for @course, html: {class: "form-horizontal"} do |f| %>
	<fieldset class="col-md-offset-3 col-md-6">
		<legend><%= form_title  %></legend>
		<div class="form-group">
			<%= f.text_field :title, class: "form-control", placeholder: "Course Title", autofocus: true  %>				
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.text_field :desc, class: "form-control", placeholder: "Course Description"  %>				
		</div>	<!-- closes form-group -->
		<div class="form-group">
			<%= f.text_field :schedule, class: "form-control", placeholder: "Course Semester/Schedule"  %>				
		</div>	<!-- closes form-group -->
		<!-- <div class="form-group"> -->
			<!-- <%#= f.text_field :course_time_zone, class: "form-control", placeholder: "Course Time Zone"  %>	 -->	
		<!-- </div> -->	<!-- closes form-group -->
		<div class="form-group">
			<%= f.submit button_label, class: "btn btn-form btn-warning"  %>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/courses/_course_preview.html.erb
<!-- _course_preview.html.erb -->
<!-- just shows course title and has a link to that course's detail page -->
<div class="row">
	<p><%= course.id %> <%= link_to course.title, course_path(course.id) %> <%=  course.desc  %></p>
</div>

app/views/courses/edit.html.erb
<!-- edit.html.erb -->
<% @page_title = "Edit Course" %>
<%= render partial: "users/user_navbar", locals: {user: @user, page_title: "Edit Course"} %>

	<div class="jumbotron">
		<%= render partial: "course_form", locals: {user: @user, form_title: "Edit Course", button_label: "Save Changes"}   %>
		<%= button_to "Cancel", course_path(@course.id), method: :get, class: "btn btn-form btn-danger" %>
	</div>

app/views/courses/index.html.erb
<!--Courses index.html.erb -->
<!-- Shows all courses OR all user courses -->
<% @page_title = "All Courses" %>
<%= render partial: "users/user_navbar", locals: {user: @user, page_title: "All Courses"} %>

<%= render partial: "shared/start_main_section"  %>
	<div class="small-spacer"></div>
	<% for course in @courses.order(:id) %>
		<h4><%= render partial: "course_preview", locals: {course: course, user: @user }  %></h4>
	<% end %>
<%= render partial: "shared/end_main_section"  %>
<%= render partial: "shared/start_sidebar"  %>
		<% if @current_user %>
			<%= render partial: "shared/start_new_poll", locals: {link_class: "btn btn-sidebar btn-primary"}  %>
			<br><br>
			<%= render partial: "shared/create_new_course", locals: {link_class: "btn btn-sidebar btn-danger"}  %>
		<% else %>
			<%= render partial: "shared/participate", locals: {link_class: "btn btn-primary btn-form"} %>
		<% end %>
<%= render partial: "shared/end_sidebar"  %>

app/views/courses/new.html.erb
<!-- new.html.erb -->
<% @page_title = "New Course" %>
<%= render partial: "users/user_navbar", locals: {user: @user, page_title: "New Course"} %>

	<div class="jumbotron">
		<%= render partial: "course_form", locals: {user: @user, course: @course, form_title: "New Course", button_label: "Save New Course"}   %>
		<%= button_to "Cancel", courses_path, method: :get, class: "btn btn-form btn-danger" %>
	</div>

app/views/courses/show.html.erb
<!-- show.html.erb -->
<% @page_title = "Course Details" %>

<%= render partial: "users/user_navbar", locals: {user: @user, page_title: "Course Details"} %>
<%= render partial: "shared/start_main_section"  %>
		<h2><%= @course.title  %></h2><br>
		<h4>Details: </h4><h4 class="indent"> <%=  @course.desc %> </h4>
		<h4>Schedule: </h4><h4 class="indent"><%= @course.schedule  %></h4>
		<!-- <h4>Timezone: <%#= @course.course_time_zone  %></h4> -->

		<div class="small-spacer"></div>
		<div class="polls-for-course">
			<h4>Polls for this course</h4>
			<% if @course.polls.count > 0%>
				<% for poll in @polls.order(:id) do  %>
					<% if @current_user == true %>
						<h5><%= render partial: "polls/poll_preview", locals: {poll: poll, path: "user"}  %></h5>
					<% else %>
						<h5><%= render partial: "polls/poll_preview", locals: {poll: poll, path: "course"}  %></h5>
					<% end %>
				<% end %>
			<% else %>
				<h5 class="indent">No polls yet</h5>
			<% end %>
			<div class="small-spacer"></div>
		</div>
<%= render partial: "shared/end_main_section"  %>
<%= render partial: "shared/start_sidebar"  %>
		<!-- show users involved with the course? -->
		<!-- whether current user is enrolled -->
		<!-- users preview partial -->
		<% if @current_user %>
			<div class="small-spacer"></div>
			<% if @user_affiliated %> <!-- user is already part of the course -->
				<%= render partial: "shared/start_new_poll", locals: {link_class: "btn btn-sidebar btn-primary"}  %>
				<br><br>
				<%= link_to "Leave course", leave_course_path(@course.id), method: :post, class: "btn btn-md btn-warning" %>
				<%= link_to 'Edit course', edit_course_path(@course.id), class: "btn btn-md btn-info"  %>
			<% else %> <!-- user is not part of the course -->
				<%= link_to "Join course", join_course_path(@course.id), method: :post, class: "btn btn-md btn-primary" %>
			<% end %>
			
		<% else %>
			<%= render partial: "shared/participate", locals: {link_class: "btn btn-primary btn-form"} %>
		<% end %>

<%= render partial: "shared/end_sidebar"  %>