config/routes.rb
Rails.application.routes.draw do

  root to: 'sites#index'

  ## main routing
  resources :users do 
    resources :courses do 
      resources :polls do 
        resources :replies do
        end
      end
    end
  end

  ## for showing courses to the public
  ## to see courses the user isn't necessarily in
  resources :courses do 
    resources :polls do
    end
  end

  ## for creating new polls, only links user and polls they created
  resources :users do 
    resources :polls do 
    end
  end

  ## for showing all replies by a specific user
  # resources :users do 
  #   resources :replies do 
  #   end 
  # end

  post '/join_course' => 'courses#join_course'
  post '/leave_course' => 'courses#leave_course'

  post 'send_sms' => 'sendtexts#send_text_message'
  # get 'send_sms' => 'sendtexts#send_text_message'
  post 'sms' => 'receive_messages#index'
  # ## testing
  get 'sms' => 'receive_messages#index'

  # post '/search', to: 'replies#search'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  # for development only
  get '/logout' => 'sessions#destroy'
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

	## Sites Controller directs to the root page which does not require security.  The only concern is that logged in users should not be able to logon again

	# before_action :is_authenticated?
	# before_filter :is_authenticated?, :except => :index

	def index

	end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/index.html.erb
<!-- <div class="container">  -->
<!-- <div class="row"> -->
<!-- <div class="col-sm-1"></div> --> <!-- creates space on left -->
<!-- <div class="col-sm-10 backdrop"> --> <!-- has translucent white background -->
<!-- <div class="row"> -->

		<div class="jumbotron">
			<div>
				<h1>Fist of Five</h1>
			</div>
			<!-- display flash messages -->
			<% flash.each do |k,v| %>
				<h2 id="<%= k %>"><%= v %></h2>
			<% end %>
			<div class="small-spacer"></div>
			<%= link_to "Log in", login_path, method: :get, class: "btn btn-danger btn-lg"  %>
			<%= link_to "Sign up", signup_path, method: :get, class: "btn btn-warning btn-lg"  %>
			<br>
			<br>
			<%= button_to "Browse Courses and Poll Results", courses_path, method: :get, class: "btn btn-default btn-lg"  %>
			<div class="small-spacer"></div>
			<div class="row">
				<div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6" id="about-text">
					<a href="https://github.com/lisavogtsf/fistOfFive/blob/master/README.md" >
					<h4>An app that allows a user to request and receive feedback by SMS and visualize the results. <span class="centered">Click to learn more.</span></h4></a>
				</div>
			</div>
		</div><!-- closes jumbotron -->

		